project:
  type: website
  output-dir: docs

website:
  title: "Neva Morgan ESS330 - Lab 6"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    self-contained: true

editor: visual

