project:
  type: website

website:
  title: "nevamorgan-lab6.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    self-contained: true

editor: visual

