project:
  type: website
  output-dir: docs

website:
  title: "nevamorgan-lab6.github.io"
  navbar:
    left:
      - href: home.qmd
        text: Home
      - index.qmd
      - nm-hyperparameter-tuning.qmd

format:
  html:
    self-contained: true

editor: visual

